utilizadores/urls.py
from django.urls import path, include
from .views import consultar_utilizadores
from .views import escolher_perfil
from .views import criar_utilizador
from .views import apagar_utilizador
from .views import alterar_utilizador
from .views import concluir_registo
from .views import home
from .views import login_action
from .views import logout_action
from .views import mensagem
from .views import alterar_password

from . import views

app_name = 'utilizadores'


urlpatterns = [
    path('consultarutilizadores', consultar_utilizadores.as_view(), name='consultar-utilizadores'), #por fazer
    path('escolherperfil', escolher_perfil, name='escolher-perfil'),    #feito
    path('criarutilizadores/<int:id>', criar_utilizador, name='criar-utilizador'), #feito
    path('alterarpassword',alterar_password,name='alterar-password'), #

    path('apagarproprioutilizador', views.apagar_proprio_utilizador,name='apagar-conta'),
    path('apagarutilizador/<int:id>', views.apagar_utilizador,name='apagar-utilizador'),
    path('alterarutilizadoradmin/<int:id>', views.alterar_utilizador_admin,name='alterar-utilizador-admin'), #
    path('alterarutilizador', views.alterar_utilizador,name='alterar-utilizador'), #
    path('validarutilizador/<int:id>', views.validar_utilizador,name='validar-utilizador'),
    path('rejeitarutilizador/<int:id>', views.rejeitar_utilizador,name='rejeitar-utilizador'),
    path('alteraridioma', views.alterar_idioma,name='alterar-idioma'),


    path('concluirregisto/<int:id>', concluir_registo,name='concluir-registo'), #
    path('mensagem/<int:id>', mensagem,name='mensagem'), #
    path('validar/<str:nome>/<int:id>', views.enviar_email_validar,name='validar'),
    path('rejeitar/<str:nome>/<int:id>', views.enviar_email_rejeitar,name='rejeitar'),
    path("logout", logout_action, name="logout"), # feito
    path("login", login_action, name="login"),   #feito

    
    path('mudarperfilescolha/<int:id>', views.mudar_perfil_escolha_admin,name='mudar-perfil-escolha-admin'),    
    path('mudarperfil/<int:tipo>/<int:id>', views.mudar_perfil_admin, name='mudar-perfil-admin'),

    path('mudarmeuperfilescolha', views.mudar_perfil_escolha,name='mudar-perfil-escolha'), #   
    path('mudarmeuperfil/<int:tipo>', views.mudar_perfil, name='mudar-perfil'), #

]       

utilizadores/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db.models import Q
from datetime import datetime,timedelta

class Utilizador(User):
    contacto = models.CharField(max_length=20)
    valido = models.CharField(max_length=255)

    def getProfiles(self):
        type = ''
        if Administrador.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Administrador')
        if Cliente.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Cliente')
        if Funcionario.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Funcionario')
        return type
    
    def concat(self, type, string):
        if type == '':
            type = string
        else:
            type += ', '+string
        return type

    @property
    def firstProfile(self):
        return self.getProfiles().split(' ')[0]
    
    def getUser(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name = "Cliente").exists():
            result = Cliente.objects.get(id=self.id)
        elif user.groups.filter(name = "Administrador").exists():
            result = Administrador.objects.get(id=self.id)
        elif user.groups.filter(name = "Funcionario").exists():
            result = Funcionario.objects.get(id=self.id)
   
        else:
            result = None
        return result   
    
    def getProfile(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name = "Cliente").exists():
            result = "Cliente"
        elif user.groups.filter(name = "Administrador").exists():
            result = "Administrador"
        elif user.groups.filter(name = "Funcionario").exists():
            result = "Funcionario"
        else:
            result = None
        return result 

    def emailValidoUO(self,uo):
        user = User.objects.get(email=self.email)
        if user.groups.filter(name = "Cliente").exists():
            utilizador = Cliente.objects.get(email=self.email)
        elif user.groups.filter(name = "Administrador").exists():
            return True
        elif user.groups.filter(name = "Funcionario").exists():
            utilizador = Funcionario.objects.get(email=self.email)
        else:
            return False
        if utilizador.faculdade == uo:
            return True
        else:
            return False  

    def emailValidoCliente(self):
        user = User.objects.get(email=self.email)
        if user.groups.filter(name = "Administrador").exists():
            return True
        else:
            return False  
    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name
    class Meta:
        db_table = 'Utilizador'






class Administrador(Utilizador):
    class Meta:
        db_table = 'Administrador'


class Cliente(Utilizador):
    nif = models.IntegerField(db_column='NIF', blank=True, null=True)  # Field name made lowercase.
    morada = models.CharField(db_column='Morada', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_nascimento = models.DateTimeField(auto_now=False, auto_now_add=False, db_column='Data de nascimento', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    class Meta:
        db_table = 'Cliente'

class Funcionario(Utilizador):
    funcao = models.CharField(db_column='Funcao', max_length=255, blank=True, null=True)  # Field name made lowercase.
    class Meta:
        db_table = 'Funcionario'


def list_to_queryset(model, data):
    from django.db.models.base import ModelBase
    if not isinstance(model, ModelBase):
        raise ValueError(
            "%s must be Model" % model
        )
    if not isinstance(data, list):
        raise ValueError(
            "%s must be List Object" % data
        )
    pk_list = [obj.pk for obj in data]
    return model.objects.filter(pk__in=pk_list)

utilizadores/templates/utilizadores/alterar_utilizador_admin.html
{% extends 'template_base.html' %}



{% block PageTittle %}- Alterar Utilizador {{nome}} {% endblock %}


{% block loggedInContent %}

<div>





  {% if registo == 1 or registo == 5 %}
  <form method="post">
    {% csrf_token %}
    {% elif registo == 2  %}
    <form method="post" id="ProfessorUniversitarioRegisterForm"
      data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}" novalidate>
      {% csrf_token %}
      {% elif registo == 3  %}
      <form method="post" id="CoordenadorRegisterForm"
        data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}" novalidate>
        {% csrf_token %}
        {% elif registo == 4  %}
        <form method="post" id="ColaboradorRegisterForm"
          data-departamentos-url="{% url 'utilizadores:ajax_load_departamentos' %}"
          data-cursos-url="{% url 'utilizadores:ajax_load_cursos' %}" novalidate>
          {% csrf_token %}
          {% endif %}

          <div style="padding: 1rem 2vw 0px;">
            <nav class="breadcrumb" aria-label="breadcrumbs">
              <ul>
                <li><a href="{% url 'homepage' %}">Início</a></li>
                <li class="is-active"><a href="{% url 'utilizadores:consultar-utilizadores' %}"
                    aria-current="page">Alterar Perfil</a></li>
              </ul>
            </nav>
            <div class="table ">
              <hr>
              <h2 class="title has-text-grey is-uppercase" style="font-size: 0.9rem;">
                {{perfil}}
              </h2>
              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Nome Próprio</label>
                    <div class="control is-clearfix">
                      <input name="first_name" class="input" id="id_first_name"
                        value="{{form.first_name.value|default_if_none:"" }}" style="" type="text" maxlength="255">
                      <!---->
                      <!---->
                      <!---->
                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Apelido</label>
                    <div class="control is-clearfix">


                      <input name="last_name" class="input" id="id_last_name" style=""
                        value="{{form.last_name.value|default_if_none:"" }}" type="text" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>

                <hr>
              </div>


              <div class="columns">

                <div class="column">
                  <div class="field">
                    <label class="label">Email</label>
                    <div class="control is-clearfix">
                      <input class="input" name="email" id="id_email" value="{{form.email.value|default_if_none:"" }}"
                        type="text" style="" maxlength="255">
                      <!---->
                      <!---->
                      <!---->
                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Contacto</label>
                    <div class="control is-clearfix">

                      <input name="contacto" class="input" id="id_contacto"
                        value="{{form.contacto.value |default_if_none:"" }}" style="" type="text" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>



              {% if registo == 2 or registo == 3 %}

              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Faculdade</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.faculdade}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Departamento</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.departamento}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Gabinete</label>
                    <div class="control is-clearfix">
                      <input class="input" name="gabinete" id="id_gabinete"
                        value="{{form.gabinete.value|default_if_none:"" }}" type="text" style="" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% elif registo == 4%}


              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Faculdade</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.faculdade}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Departamento</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.departamento}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Curso</label>
                    <div class="control is-clearfix">

                      <div class="field">
                        <!---->
                        <div class="control is-expanded">
                          <span class="select is-fullwidth is-empty">
                            {{form.curso}}
                          </span>
                          <!---->
                        </div>
                        <!---->
                      </div>

                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% elif registo == 5%}

              <div class="columns" style="margin-right:66.6%;">
                <div class="column">
                  <div class="field">

                    <label class="label">Gabinete</label>
                    <div class="control is-clearfix">
                      <input class="input" name="gabinete" id="id_gabinete"
                        value="{{form.gabinete.value|default_if_none:"" }}" type="text" style="" maxlength="255">
                    </div>
                    <!---->
                  </div>
                </div>
                <hr>
              </div>
              {% endif %}
              <div style="margin-top:2%;text-align:center;position:center;">
                <a href="{% url 'utilizadores:consultar-utilizadores' %}" aria-current="page">
                <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%">Voltar</button>
                </a>

                {% if perfil == "Participante" %}
                  <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste participante a sua <b>incrição</b> será apagada permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                {% elif perfil == "Colaborador" %}
                  <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste colaborador as suas <b>tarefas</b> deixarão de lhe estar atribuidas.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                {% elif perfil == "Professor Universitario" %}
                  <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste professor universitário as suas <b>atividades</b> serão apagadas permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                {% elif  perfil == "Coordenador" %}
                  <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste coordenador as <b>atividades dos departamentos</b> pelo qual está responsável serão apagadas permanentemente.<br><br>As <b>tarefas dos colaboradores</b> pelo qual este coordenador está responsável serão apagadas permanentemente.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                {% elif  perfil == "Administrador" %}
                  <a
                  onclick="alert.render('<b>Atenção!</b><br><br>Ao alterar o perfil deste administrador todas as suas <b>informações</b> serão apagadas frequentemente incluindo os <b>dados de configuração</b> do dia aberto pelo qual este administrador está responsável.','{% url 'utilizadores:mudar-perfil-escolha-admin' id %}')">
                {% endif %}
                 
                    <button type="button" class="button is-link is-outlined" style="margin-right:5%">Escolher outro perfil</button>
                  </a>


                        <button style="" type="submit" class="button is-success is-outlined">
                          <span>Confirmar</span>
                        </button>
              </div>
        </form>




        {% if msg %}
        <div style="margin-left:30%;margin-right:30%; margin-top:%">
          <div style="margin-top:2%;text-align: center;position:center;">
            <article class="message is-danger">
              <div class="message-body">
                <p style="text-align: center;">
                  {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                  <p style="color: #ff0000; text-align:center">{{error}}</p>
                  {% endfor %}
                  {% endif %}
                  {% for error in erros %}
                  <p style="color: #ff0000; text-align:center">{{error}}</p>
                  {% endfor %}

                
                  {% for field in form %}
                  {% for error in field.errors %}
                  {% if field.name == "email" %}
                  <p style="color: #ff0000;">{{ error }}</p>
                  {% endif %}
                  {% endfor %}
                  {% endfor %}



                </p>
              </div>
            </article>
          </div>
        </div>
        {% endif %}
</div>
</div>
</div>

{% endblock %}




{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>


  {% if registo == 2 %}
  $("#id_faculdade").change(function () {
    var url = $("#ProfessorUniversitarioRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);
      }
    });

  }); 
  {% elif registo == 3 %}
  $("#id_faculdade").change(function () {
    var url = $("#CoordenadorRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);
      }
    });

  }); 
  {% elif registo == 4 %}
  $("#id_faculdade").change(function () {

    var url = $("#ColaboradorRegisterForm").attr("data-cursos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_curso").html(data);

      }
    });

  });
  $("#id_faculdade").change(function () {

    var url = $("#ColaboradorRegisterForm").attr("data-departamentos-url");
    var faculdadeid = $(this).val();

    $.ajax({
      url: url,
      data: {
        'faculdade': faculdadeid
      },
      success: function (data) {
        $("#id_departamento").html(data);

      }
    });

  }); {% endif %}
</script>
{% endblock scripts %}

utilizadores/templates/utilizadores/concluir_registo.html
{% load static %}
<!doctype html>
<html>
<head>
    <head>
        <meta charset="utf-8">
        <title>LES</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
    
        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">
    
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    
        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <style>
          p, h2 {
            width: 90%;
            margin: auto;
        }
        h2 {
            text-align: center;
        }
        p {
            color: black;
        }
        .input, .input1 {
            outline: none;
            border: 3px double black;
            width: 50%;
            color: #757575;
            border-radius: 5px;
        }
        ul {
            color: red;
            margin-left: 3.75%;
        }
        hr{
            width: 50%;
            margin-left: 25%;
        }
        </style>
    </head>
<body>


{% block content %}



{% block loggedInOutContent %}

<div>


    <div style="padding: 3rem 2vw 1rem;">

        <div class="steps is-success">

            

            </div>

        </div>


            <div style="margin-bottom:3%;margin-top:3%;">
                <h2 class="title is-5 text-primary" style="text-align: center;" >Registo feito com sucesso!</h2>
            </div>
    
    </div>

    <div style="text-align: center;position:center;margin-top:4%">
        {% if participante == "Admin" %}
        <a href="{% url 'utilizadores:consultar-utilizadores' %}">
            <button  class="button btn btn-lg btn-primary">Continuar</button>
        </a>
        {% else %}
        <a href="{% url 'homepage' %}">
            <button  class="button btn btn-lg btn-primary">Continuar</button>
        </a>
        {% endif %}
    </div>

    {% endblock %}

</div>

{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

utilizadores/templates/utilizadores/consultar_utilizadores.html
{% extends 'base.html' %}

{% load django_tables2 %}
{% load static %}
{% block content %}

{% block loggedInContent %}
<div class="columns">
    <div class="column is-3">
        <div class="menu" style="margin-left: 5%">
            <br>
            <h2 class="text-primary" style="text-align:center">Consultar Utilizadores</h2>
            <div class="menu-label" >
                Filtros Utilizadores:
            </div>
            <form method="get">
                <p class="menu-list">
                    <li>
                        <div class="field">
                            <div class="control has-icons-left">
                                <input class="input" style="outline: none;
                                border: 3px double black;
                                width: 25%;
                                color: #757575;
                                border-radius: 5px;" name="{{ filter.form.nome.name }}" 
                                    value="{{ filter.form.nome.value|default_if_none:'' }}" type="text"
                                    placeholder="Nome">
                                <span class="icon is-left">
                                    <i class="mdi mdi-magnify mdi-24px"></i>
                                </span>
                            </div>
                        </div>
                        <br>
                        <div class="field">
                            <label>Tipos:</label>
                        </div>
      
                            {% for value, label in filter.form.fields.groups.choices %}
                            <div class="field" style="padding-left: 1rem;">
                                <label class="checkbox">
                                    <input type="checkbox" name="{{filter.form.groups.name}}"
                                        value="{{value|stringformat:'s'}}"
                                        {% if value|stringformat:'s' in filter.form.groups.value %}checked{% endif %}>
                                    {% if label == "ProfessorUniversitario" %}Professor
                                    Univesitário{% else %}{{label}}{% endif %}
                                </label>
                            </div>
                            {% endfor %}
                        </ul>
                    </li>
<br>
                        <div class="field">
                            <label>Estados:</label>
                        </div>
                            {% for value, label in filter.form.fields.valido.choices %}
                            <div class="field" style="padding-left: 1rem;">
                                <label class="checkbox">
                                    <input type="checkbox" name="{{filter.form.valido.name}}"
                                        value="{{value|stringformat:'s'}}"
                                        {% if value|stringformat:'s' in filter.form.valido.value %}checked{% endif %}>
                                    {{label}}
                                </label>
                            </div>
                            {% endfor %}
                </ul>
                <br>
                <div class="field is-grouped">
                    <p class="control is-expanded">
                        <button class="button is-primary is-fullwidth btn btn-sm btn-primary" type="submit">
                            <span class="icon">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                            <span>Pesquisar</span>
                        </button>
                        &nbsp&nbsp&nbsp
                        <input class="button is-light is-fullwidth btn btn-sm btn-primary" type="reset"
                            onclick="event.preventDefault(); window.location='{% url 'utilizadores:consultar-utilizadores' %}';"
                            value="Limpar">
                    </p>
                </div>
            </form>
        </div>
    </div>
    <div class="column">
        {% render_table table 'utilizadores/consultar_utilizadores_tabela.html' %}
    </div>
</div>
{% endblock %}
{% endblock %}

utilizadores/templates/utilizadores/departamento_dropdown_list_options.html
<option value="">---------</option>
{% for departamento in departamentos %}
<option value="{{ departamento.id }}">{{ departamento.nome }}</option>
{% endfor %}

utilizadores/templates/utilizadores/enviar_email_rejeitar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>

  <title>
    Event Manager {% block title %} {% endblock title %}
 
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="1; {% url 'utilizadores:rejeitar-utilizador' id %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
     <link rel="icon" href="{% static 'img/logo.png' %}"/>
</head>
<body>
<div class="pageloader is-active"><span class="title">{{msg}}</span></div>


</body>
</html>

utilizadores/templates/utilizadores/enviar_email_validar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>

  <title>
    Event Manager {% block title %} {% endblock title %}
 
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="1; {% url 'utilizadores:validar-utilizador' id %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
     <link rel="icon" href="{% static 'img/logo.png' %}"/>
</head>
<body>
<div class="pageloader is-active"><span class="title">{{msg}}</span></div>

</body>
</html>